# Generated by Django 4.0.5 on 2022-06-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('for_sale', 'for_sale'), ('ready_to_build', 'ready_to_build')], max_length=20, verbose_name='status')),
                ('price', models.FloatField(verbose_name='price')),
                ('bed', models.IntegerField(verbose_name='bed')),
                ('bath', models.IntegerField(verbose_name='bath')),
                ('acre_lot', models.FloatField(verbose_name='acre_lot')),
                ('full_address', models.TextField(verbose_name='full_address')),
                ('street', models.TextField(verbose_name='street')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=10, verbose_name='state')),
                ('zip_code', models.FloatField(verbose_name='zip_code')),
                ('house_size', models.FloatField(verbose_name='house_size')),
                ('sold_date', models.DateField(verbose_name='sold_date')),
            ],
        ),
    ]
